# This docker compose file will create a test cluster for freeipa
# Requires freeipa/freeipa-server:centos-7.4
# Builds two master servers and two satellite servers
#
version: "3.9"

services:
  
  master1:
    image: freeipa-test:2.0
    container_name: ipa-master-1
    hostname: ipa-master-1.test.local
    build:
      context: .
      dockerfile: ipa.Dockerfile
      args:
        Dom_Name: test.local
        Host_1: ipa-master-2:172.18.1.12
        Host_2: ipa-satellite-1:172.18.1.21
        Host_3: ipa-satellite-2:172.18.1.22
    networks:
      ipa-test:
        ipv4_address: 172.18.1.11
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - cgroup:/sys/fs/cgroup:z
      - ipa-data:/Data:z

  master2:
    image: freeipa-test:2.0
    container_name: ipa-master-2
    hostname: ipa-master-2.test.local
    build:
      context: .
      dockerfile: ipa.Dockerfile
      args:
        Dom_Name: test.local
        Host_1: ipa-master-1:172.18.1.11
        Host_2: ipa-satellite-1:172.18.1.21
        Host_3: ipa-satellite-2:172.18.1.22
    networks:
      ipa-test:
        ipv4_address: 172.18.1.12
    ports:
      - "8081:80"
      - "4434:443"
    volumes:
      - cgroup:/sys/fs/cgroup:z
      - ipa-data:/data:z

  satellite1:
    image: freeipa-test:2.0
    container_name: ipa-satellite-1
    hostname: ipa-satellite-1.test.local
    build:
      context: .
      dockerfile: ipa.Dockerfile
      args:
        Dom_Name: test.local
        Host_1: ipa-master-1:172.18.1.11
        Host_2: ipa-master-2:172.18.1.12
        Host_3: ipa-satellite-2:172.18.1.22
    networks:
      ipa-test:
        ipv4_address: 172.18.1.21
    ports:
      - "8082:80"
      - "4435:443"
    volumes:
      - cgroup:/sys/fs/cgroup:ro
      - ipa-data:/data:Z

  satellite2:
    image: freeipa-test:2.0
    container_name: ipa-satellite-2
    hostname: ipa-satellite-2.test.local
    build:
      context: .
      dockerfile: ipa.Dockerfile
      args:
        Dom_Name: test.local
        Host_1: ipa-master-1:172.18.1.11
        Host_2: ipa-master-2:172.18.1.12
        Host_3: ipa-satellite-1:172.18.1.21
    networks:
      ipa-test:
        ipv4_address: 172.18.1.22
    ports:
      - "8083:80"
      - "4436:443"
    volumes:
      - cgroup:/sys/fs/cgroup:ro
      - ipa-data:/data:Z

  client1:
    container_name: client-1
    hostname: client-1.test.local
    image: ubuntu:latest
    networks:
      ipa-test:
        ipv4_address: 172.18.1.31

  client2:
    container_name: client-2
    hostname: client-2.test.local
    image: ubuntu:latest
    networks:
      ipa-test:
        ipv4_address: 172.18.1.32

networks:
  ipa-test:
    name: ipa-test
    ipam:
      driver: default
      config:
        - subnet: "172.18.1.0/24"

volumes:
  cgroup: {}
  ipa-data: {}
