# YAML parameters file to define a FreeIPA cluster

## Node specific info
Node_FQDN: 'ipa-master-1.test.local'
Volumes:
  #'/etc/ntp.conf:/etc/ntp.conf:ro,
  #/etc/localtime:/etc/localtime:ro,
  #/etc/timezone:/etc/timezone:ro'

## External DNS info
Zone_Rev_IP: '01.002.03.in-addr.arpa'
Zone_Fwd_DNS: 'ipa.test.local'

## Cluster info
# Define domain
Domain_Name: 'test.local'

# Define cluster master node hostnames and IP adresses
Master_Nodes:
  MASTER_1: 
    - 'ipa-master-1'
    - '172.18.1.11'
  MASTER_2: 
    - 'ipa-master-2'
    - '172.18.1.12'

# Define cluster satellite node hostnames and IP addresses
Satellite_Nodes:
  SAT_1:
    - 'ipa-satellite-1'
    - '172.18.1.21'
  SAT_2:
    - 'ipa-satellite-2'
    - '172.18.1.22'

# Define cluster test client node hostnames and IP addresses
Client_Nodes:
  CLIENT_1:
    - 'client-1'
    - '172.18.1.31'
  CLIENT_2:
    - 'client-2'
    - '172.18.1.32'

# Define IPA Image
Container_Image: 'ipa:1.0'
Docker_File: 'ipa.Dockerfile'

## IPA Install
# Master1 Node Options
Master1_Command: 'ipa-server-install'
Master1_Options:
  - 'reverse-zone=VAL'
  - 'realm=VAL'
  - 'hostname=VAL'
  - 'ds-password=VAL'
# Master2 Node Options
Master2_Options:
  - 'setup-ca'
# Satellite Node Options
Replica_Command: 'ipa-replica-install'
Replica_Options:
  - 'server=VAL'
  - 'principal=VAL'
# All Node Options
IPA_Install_Options:
  - 'unattended'
  - 'no-ntp'
  - 'mkhomedir'
  - 'no-host-dns'
  - 'setup-dns'
  - 'no-dnssec-validation'
  - 'auto-forwarders'
  - 'allow-zone-overlap'
  - 'domain=VAL'
  - 'admin-password=VAL'
