---
# Ansible playbook to perform post-spin build steps on bastion nodes
# Usage: ansible-playbook -i inventory.yml bastion_install.yml
# Runs against IPs/Hostnames in hosts file
#
- hosts: bastion
# Set Variables
  vars:
    domain_name: "unit21.ai"
    host_fqdn: "{{ host_name }}.{{ domain_name }}"
    psql_version: "12"
    snowsql_url: "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/"
    snowsql_installer: "snowsql-1.2.9-linux_x86_64.bash"
    appdir_path: "/opt/app"
    cronjobs_path: "{{ appdir_path }}/cronjobs"
    github_unit21_path: "{{ appdir_path }}/unit21-github"
    github_bastion_path: "{{ github_unit21_path }}/bastion-cronjobs"
    github_cronjobs_path: "{{ appdir_path }}/unit21-github/bastion-cronjobs/cronjobs"
#
# Config Block
  gather_facts: True
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
#
## Run Tasks
  tasks:
#
# Initial Setup
    - name: Populate Service Facts
      ansible.builtin.service_facts:

    - name: Update Hosts File - Comment
      lineinfile:
        insertafter: EOF
        create: yes
        path: /etc/hosts
        search_string: "Hostname Resolution"
        line: "# Hostname Resolution"
        state: present

    - name: Update Hosts File - Host
      lineinfile:
        insertafter: "Hostname Resolution"
        create: yes
        path: /etc/hosts
        search_string: "{{ private_ip }}"
        line: "{{ private_ip }}\t{{ host_fqdn }}"
        state: present

    - name: Set Hostname
      hostname:
        name: "{{ host_fqdn }}"
        use: systemd

    - name: Check For and Install Updates
      apt:
        update_cache: yes
        upgrade: full

    - name: Create GitHub Group
      group:
        name: git
        state: present

    - name: Add User to Git Group
      user:
        name: "{{ user }}"
        groups: admin,git
        append: yes

#
# Create Directories and Files
    - name: Create Secrets Bash File
      template:
        src: "secrets.sh"
        dest: "{{ appdir_path }}/secrets.sh"
        owner: "{{ user }}"
        group: admin
        mode: 0777

    - name: Create Celery Flower Directory
      file:
        path: /home/ubuntu/celery-flower
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0774

    - name: Create Snowsql Directory
      file:
        path: /home/ubuntu/.snowsql
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0770

    - name: Create Snowsql Config File
      template:
        src: "snowsql.conf"
        dest: /home/ubuntu/.snowsql/config
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0660

    - name: Create Unit21 GitHub Directory
      file:
        path: "{{ github_unit21_path }}"
        state: directory
        owner: "{{ user }}"
        group: git
        mode: 0774

    - name: Upload GitHub Key
      template:
        src: "bastion_cronjobs.priv"
        dest: /home/ubuntu/.ssh/bastion_cronjobs.priv
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

    - name: Configure Unit21 GitHub SSH
      blockinfile:
        create: yes
        path: /home/ubuntu/.ssh/config
        block: "host unit21.git\n\tHostName github.com\n\tIdentityFile ~/.ssh/bastion_cronjobs.priv\n\tForwardAgent yes"
        state: present
#
# Package Management
    - name: Install Vim
      package:
        name: vim
        state: latest

    - name: Install pip
      package:
        name: python3-pip
        state: latest

    - name: Install AWS CLI
      package:
        name: awscli
        state: latest

    - name: Install boto3 Module
      package:
        name: python3-boto3
        state: latest

    - name: Install botocore Module
      package:
        name: python3-botocore
        state: latest

    - name: Install OpenJDK
      package:
        name: default-jre
        state: latest

    - name: Install kafka
      package:
        name: librdkafka1
        state: latest

    - name: Install Redis
      package:
        name: redis
        state: latest

    - name: Install Redis Module
      package:
        name: python3-redis
        state: latest

    - name: Install ElasticSearch Module
      package:
        name: python3-elasticsearch
        state: latest

    - name: Install JQ
      package:
        name: jq
        state: latest

    - name: Install PSQL
      package:
        name: postgresql-client-{{ psql_version }}
        state: latest

    - name: Install zookeeperd
      package:
        name: zookeeperd
        state: latest

    - name: Install Celery Module
      package:
        name: python3-celery
        state: latest

    - name: Install Flower Module
      shell:
        cmd: pip3 install flower
      args:
        executable: /bin/bash
      when: ansible_facts.services['flower.service'] is not defined

    - name: Install psycopg2 Module
      package:
        name: python3-psycopg2
        state: latest

    - name: Install NFS Common
      package:
        name: nfs-common
        state: latest

    - name: Install LibNFS Utilities
      package:
        name: libnfs-utils
        state: latest

    - name: Install Unzip
      package:
        name: unzip
        state: latest

    - name: Install Git
      package:
        name: git
        state: latest

    - name: Check if SnowSQL Is Installed
      stat:
        path: /bin/snowsql
      register: check_snowsql

    - name: Download SnowSQL (Snowflake)
      get_url:
        url: "{{ snowsql_url }}{{ snowsql_installer }}"
        dest: /tmp
        mode: 0777
      when: check_snowsql.stat.isreg is not defined

    - name: Install SnowSQL (Snowflake)
      shell: SNOWSQL_DEST="/bin" SNOWSQL_LOGIN_SHELL="/home/ubuntu/.profile" bash "/tmp/{{ snowsql_installer }}"
      args:
        executable: /bin/bash
      when: check_snowsql.stat.isreg is not defined
# 
# Configure Services
    - name: Set Up Flower Service
      template:
        src: "flower.service"
        dest: /etc/systemd/system/flower.service
      notify:
      - restart systemd
      - restart flower

    - name: Clone Bastion-Cronjobs Repo
      become: no
      git:
        ssh_opts: "-F /home/ubuntu/.ssh/config"
        clone: yes
        repo: git@unit21.git:u21/bastion-cronjobs.git
        version: master
        accept_hostkey: yes
        dest: "{{ github_bastion_path }}"
        update: yes

    - name: Symlink Cronjobs Dir
      file:
        src: "{{github_cronjobs_path}}"
        path: "{{ cronjobs_path}} "
        state: link
#
# Check Services
    - debug:
        msg: Flower service is RUNNING.
      when: ansible_facts.services['flower.service']['state'] == 'running'

    - debug:
        msg: Flower service is NOT running!
      when: ansible_facts.services['flower.service']['state'] != 'running'
#
# Set Handlers
  handlers:
    
    - name: restart flower
      service:
        name: flower
        state: restarted

    - name: restart systemd
      service:
        name: daemon-reload
        state: restarted

