---
# Ansible playbook to perform full package updates
# Usage: ansible-playbook -i inventory.yml bastion_package_update.yml
# Runs against IPs/Hostnames in hosts file
#
- hosts: bastion
# Set Variables
  vars:
    domain_name: "unit21.ai"
    host_fqdn: "{{ host_name }}.{{ domain_name }}"
#
# Config Block
  gather_facts: False
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
#
## Run Tasks
  tasks:
    - name: Check For and Install Updates
      apt:
        update_cache: yes
        upgrade: full

